package edu.colostate.cs.cs414.enigma.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * The persistent class for the membership database table.
 * 
 */
@Entity
@Table(name="membership")
@NamedQueries({
	@NamedQuery(name="Membership.findAll", query="SELECT m FROM Membership m"),
	@NamedQuery(name="Membership.findType", query="SELECT m FROM Membership m WHERE m.type = :type")
})
public class Membership implements Serializable {
	private static final long serialVersionUID = 1L;

	/* Primary key generated by the database. Key must be unique, not null, and not updatable */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id", unique=true, nullable=false, updatable=false)
	private int id;

	/* Description cannot be updated once set. Also, it must be unique. */
	@Column(name="type", nullable=false, updatable=false, unique=true, length=255)
	private String type;
	
	protected Membership() {}

	public Membership(String type) {
		this.type = type;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Membership other = (Membership) obj;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Membership [id=" + id + ", type=" + type + "]";
	}
}
